name: ci.yml

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=20 <21"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'backend/package-lock.json') }}


      - name: Install dependencies
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format

      - name: Run Stylelint
        run: npm run lint:style

      - name: Run Unit Tests with coverage
        run: npm run test:coverage

      - name: Check coverage threshold (80%)
        run: |
          COVERAGE=$(node -pe "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "!!!Coverage ниже 80%!!!"
            exit 1
          fi

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run e2e Tests
        run: npx playwright test

  deploy:
    needs: check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@85.117.234.255 "
          cd ITMO-Web-Barcard
          cat > backend/.env << 'EOT'
          PORT=${{ secrets.PORT }}

          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}

          DATABASE_URL=${{ secrets.DATABASE_URL }}

          JWT_SECRET=${{ secrets.JWT_SECRET }}
          REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}
          SUPER_ADMIN_PASSWORD=${{ secrets.SUPER_ADMIN_PASSWORD }}
          JWT_EXPIRES=${{ secrets.JWT_EXPIRES }}
          BCRYPT_ROUNDS=${{ secrets.BCRYPT_ROUNDS }}
          CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}

          SMTP_HOST=${{secrets.SMTP_HOST}}
          SMTP_PORT=${{secrets.SMTP_PORT}}
          SMTP_USER=${{secrets.SMTP_USER}}
          SMTP_PASS=${{secrets.SMTP_PASS}}
          SMTP_FROM=${{secrets.SMTP_FROM}}
          APP_PUBLIC_URL=${{secrets.APP_PUBLIC_URL}}
          INVITE_SECRET=${{secrets.INVITE_SECRET}}
          EOT

          chmod 600 backend/.env
          git pull &&
          make run
          "
